[versions]
dotenv-kotlin = "6.5.1"
junit-jupiter = "6.0.0"
kotlin = "2.2.20"
kotlinx-coroutines = "1.10.2"
ktfmt = "0.24.0"

[libraries]
dotenv-kotlin = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv-kotlin" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

[plugins]
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
