[versions]
junit-jupiter = "6.0.1"
kotlin = "2.3.0"
ktfmt = "0.25.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
